# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-jessie64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.synced_folder "../data", "/vagrant"
  config.vm.synced_folder "../demovibes", "/home/vagrant/demovibes"
  config.vm.synced_folder "../media", "/home/vagrant/media"

  config.vm.provider "virtualbox" do |vb|
     vb.cpus   = "2"
     vb.memory = "1024"
  end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose  = true
    ansible.playbook = "demovibes.yml"
  end

end
